---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:

  - name: chef/ubuntu-14.04
    driver:
      box: chef/ubuntu-14.04    
      box_url: /root/.vagrant.d/boxes/chef-VAGRANTSLASH-ubuntu-14.04

# - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:

