---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learningchef/centos65

# - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:
